In [ ]:
pip install google-cloud-bigquery pandas db-dtypes

Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.13/dist-packages (3.43.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: db-dtypes in /usr/local/lib/python3.13/dist-packages (1.7.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.28.0 in /usr/local/lib/python3.13/dist-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (2.30.3)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.13/dist-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.49.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.13/dist-packages (from google-cloud-bigquery) (2.6.1)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from google-cloud-bigquery) (2.10.1)
Requirement already satisfied: packaging>=24.2.0 in /usr/local/lib/python3.13/dist-packages (from google-cloud-bigquery) (26.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.13/dist-packages (from google-cloud-bigquery) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: pyarrow>=13.0.0 in /usr/local/lib/python3.13/dist-packages (from db-dtypes) (18.1.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.13/dist-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.13/dist-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.28.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.83.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.13/dist-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.13/dist-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (50.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.13/dist-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: pyopenssl>=20.0.0 in /usr/local/lib/python3.13/dist-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (26.4.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.7.22)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.1.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (4.16.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (3.0)

In [ ]:
from google.colab import auth
auth.authenticate_user()

In [ ]:

#set google project id
project_id = 'alpine-talon-475311-f6'
print("Authenticated project:", project_id)

Authenticated project: alpine-talon-475311-f6

In [ ]:
from google.cloud import bigquery

client = bigquery.Client(project=project_id)

In [ ]:
import pandas as pd
Query = ''' SELECT *
 FROM `bigquery-public-data.biglake-public-nyc-taxi-iceberg.public_data.nyc_taxicab_2021` limit 100000'''

df = client.query(Query).to_dataframe()

In [ ]:
df

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,imp_surcharge,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month
0,2,2022-01-30 18:44:53+00:00,2022-01-31 01:58:06+00:00,1,3.000000000,1.0,N,1,11.000000000,0E-9,1.000000000,3.000000000,0E-9,0E-9,0E-9,17.000000000,229,234,2022,1
1,2,2022-01-30 05:18:31+00:00,2022-01-30 05:23:19+00:00,2,1.000000000,1.0,N,1,5.000000000,0E-9,1.000000000,2.000000000,0E-9,0E-9,0E-9,10.000000000,107,137,2022,1
2,2,2022-01-30 18:22:33+00:00,2022-01-30 18:38:36+00:00,2,1.000000000,1.0,N,1,11.000000000,0E-9,1.000000000,3.000000000,0E-9,0E-9,0E-9,17.000000000,186,170,2022,1
3,2,2022-01-01 15:42:34+00:00,2022-01-01 16:07:50+00:00,1,10.000000000,1.0,N,1,31.000000000,1.000000000,1.000000000,8.000000000,7.000000000,0E-9,1.000000000,51.000000000,138,238,2022,1
4,2,2022-01-11 14:01:55+00:00,2022-01-12 13:55:25+00:00,1,8.000000000,1.0,N,2,27.000000000,0E-9,1.000000000,0E-9,0E-9,0E-9,0E-9,30.000000000,140,160,2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-27 23:58:15+00:00,2021-01-28 00:02:38+00:00,1,1.000000000,1.0,N,1,5.000000000,3.000000000,1.000000000,1.000000000,0E-9,0E-9,None,10.000000000,236,263,2021,1
99996,1,2021-01-29 11:04:49+00:00,2021-01-29 11:10:21+00:00,2,1.000000000,1.0,N,1,5.000000000,3.000000000,1.000000000,1.000000000,0E-9,0E-9,None,9.000000000,234,90,2021,1
99997,1,2021-01-29 19:18:41+00:00,2021-01-29 19:22:59+00:00,2,1.000000000,1.0,N,1,5.000000000,4.000000000,1.000000000,1.000000000,0E-9,0E-9,None,10.000000000,161,230,2021,1
99998,1,2021-01-19 18:58:09+00:00,2021-01-19 19:02:02+00:00,1,1.000000000,1.0,N,1,5.000000000,4.000000000,1.000000000,2.000000000,0E-9,0E-9,None,11.000000000,170,229,2021,1
99999,1,2021-01-25 18:18:26+00:00,2021-01-25 18:22:58+00:00,1,1.000000000,1.0,Y,1,5.000000000,4.000000000,1.000000000,2.000000000,0E-9,0E-9,None,11.000000000,239,143,2021,1

In [ ]:
df = df.replace(0E-9,0)

/tmp/ipykernel_30557/3813967916.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(0E-9,0)

In [ ]:
df['trip_distance'] = df['trip_distance'].astype(float)
df['fare_amount'] = df['fare_amount'].astype(float)
df['mta_tax'] = df['mta_tax'].astype(float)
df['tip_amount'] = df['tip_amount'].astype(float)
df['total_amount'] = df['total_amount'].astype(float)
df['extra'] = df['extra'].astype(float)
df['tolls_amount'] = df['tolls_amount'].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   vendor_id            100000 non-null  object
 1   pickup_datetime      99870 non-null   datetime64[us, UTC]
 2   dropoff_datetime     99870 non-null   datetime64[us, UTC]
 3   passenger_count      92480 non-null   Int64
 4   trip_distance        99870 non-null   float64
 5   rate_code            92610 non-null   object
 6   store_and_fwd_flag   92610 non-null   object
 7   payment_type         100000 non-null  object
 8   fare_amount          99870 non-null   float64
 9   extra                99870 non-null   float64
 10  mta_tax              99870 non-null   float64
 11  tip_amount           99870 non-null   float64
 12  tolls_amount         99870 non-null   float64
 13  imp_surcharge        99870 non-null   float64
 14  airport_fee          314 non-null     object
 15  total_amount         99870 non-null   float64
 16  pickup_location_id   100000 non-null  object
 17  dropoff_location_id  100000 non-null  object
 18  data_file_year       99870 non-null   Int64
 19  data_file_month      99870 non-null   Int64
dtypes: Int64(3), datetime64[us, UTC](2), float64(8), object(7)
memory usage: 15.5+ MB

In [ ]:
df

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,imp_surcharge,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month
0,2,2022-01-30 18:44:53+00:00,2022-01-31 01:58:06+00:00,1,3.0,1.0,N,1,11.0,0.0,1.0,3.0,0.0,0.0,0,17.0,229,234,2022,1
1,2,2022-01-30 05:18:31+00:00,2022-01-30 05:23:19+00:00,2,1.0,1.0,N,1,5.0,0.0,1.0,2.0,0.0,0.0,0,10.0,107,137,2022,1
2,2,2022-01-30 18:22:33+00:00,2022-01-30 18:38:36+00:00,2,1.0,1.0,N,1,11.0,0.0,1.0,3.0,0.0,0.0,0,17.0,186,170,2022,1
3,2,2022-01-01 15:42:34+00:00,2022-01-01 16:07:50+00:00,1,10.0,1.0,N,1,31.0,1.0,1.0,8.0,7.0,0.0,1.000000000,51.0,138,238,2022,1
4,2,2022-01-11 14:01:55+00:00,2022-01-12 13:55:25+00:00,1,8.0,1.0,N,2,27.0,0.0,1.0,0.0,0.0,0.0,0,30.0,140,160,2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-27 23:58:15+00:00,2021-01-28 00:02:38+00:00,1,1.0,1.0,N,1,5.0,3.0,1.0,1.0,0.0,0.0,None,10.0,236,263,2021,1
99996,1,2021-01-29 11:04:49+00:00,2021-01-29 11:10:21+00:00,2,1.0,1.0,N,1,5.0,3.0,1.0,1.0,0.0,0.0,None,9.0,234,90,2021,1
99997,1,2021-01-29 19:18:41+00:00,2021-01-29 19:22:59+00:00,2,1.0,1.0,N,1,5.0,4.0,1.0,1.0,0.0,0.0,None,10.0,161,230,2021,1
99998,1,2021-01-19 18:58:09+00:00,2021-01-19 19:02:02+00:00,1,1.0,1.0,N,1,5.0,4.0,1.0,2.0,0.0,0.0,None,11.0,170,229,2021,1
99999,1,2021-01-25 18:18:26+00:00,2021-01-25 18:22:58+00:00,1,1.0,1.0,Y,1,5.0,4.0,1.0,2.0,0.0,0.0,None,11.0,239,143,2021,1

#Data Cleaning and Tansformation

In [ ]:
df['trip_duration']=(df['dropoff_datetime'] - df['pickup_datetime']).dt.total_seconds() /3600
#created a trip duration column where duration of travel is presented in hours

In [ ]:
df['trip_duration'].sort_values(ascending = False).head(10)

#trips with  duration  more than 5 hours seems  a lot suspicious

80386    23.999722
4250     23.988889
96685    23.984167
78984    23.979444
2705     23.978889
2680     23.975556
50442    23.971944
7585     23.971389
4496     23.970556
2741     23.970000
Name: trip_duration, dtype: float64

In [ ]:
df[df['trip_duration']>5].count()
# here we can see that there are 50 rows where trip duration is more than  5 hours

vendor_id              297
pickup_datetime        297
dropoff_datetime       297
passenger_count        297
trip_distance          297
rate_code              297
store_and_fwd_flag     297
payment_type           297
fare_amount            297
extra                  297
mta_tax                297
tip_amount             297
tolls_amount           297
imp_surcharge          297
airport_fee            105
total_amount           297
pickup_location_id     297
dropoff_location_id    297
data_file_year         297
data_file_month        297
trip_duration          297
dtype: int64

In [ ]:
long_trips = df[df['trip_duration']>5]

In [ ]:
long_trips[['pickup_datetime','dropoff_datetime','trip_duration','trip_distance','fare_amount']]
# from checking the trip duration ,trip distance and fare amount the anomalies are confirmed that these are really bad data

,pickup_datetime,dropoff_datetime,trip_duration,trip_distance,fare_amount
0,2022-01-30 18:44:53+00:00,2022-01-31 01:58:06+00:00,7.220278,3.0,11.0
4,2022-01-11 14:01:55+00:00,2022-01-12 13:55:25+00:00,23.891667,8.0,27.0
5,2022-01-09 10:43:54+00:00,2022-01-09 17:54:57+00:00,7.184167,2.0,9.0
86,2021-01-01 02:06:43+00:00,2021-01-02 00:56:47+00:00,22.834444,1.0,5.0
397,2021-01-01 00:54:24+00:00,2021-01-02 00:51:23+00:00,23.949722,4.0,16.0
...,...,...,...,...,...
96685,2021-01-13 17:03:36+00:00,2021-01-14 17:02:39+00:00,23.984167,1.0,4.0
97048,2021-01-16 07:29:08+00:00,2021-01-17 06:43:16+00:00,23.235556,2.0,11.0
98036,2021-01-13 10:24:36+00:00,2021-01-14 09:34:08+00:00,23.158889,2.0,8.0
99456,2021-01-31 00:07:49+00:00,2021-01-31 23:54:40+00:00,23.780833,1.0,6.0
99526,2021-01-05 11:42:56+00:00,2021-01-06 11:34:08+00:00,23.853333,3.0,12.0

In [ ]:
df2 = df.copy()
df2 = df2[df2['trip_duration']<=5]

# we are making a safe copy df so that any chages in df2 will not affect the orignal dataset

In [ ]:
df2
#so df2 is\ cleaned where the trips more than 5 hours has been filtered out

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,...,tip_amount,tolls_amount,imp_surcharge,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month,trip_duration
1,2,2022-01-30 05:18:31+00:00,2022-01-30 05:23:19+00:00,2,1.0,1.0,N,1,5.0,0.0,...,2.0,0.0,0.0,0,10.0,107,137,2022,1,0.080000
2,2,2022-01-30 18:22:33+00:00,2022-01-30 18:38:36+00:00,2,1.0,1.0,N,1,11.0,0.0,...,3.0,0.0,0.0,0,17.0,186,170,2022,1,0.267500
3,2,2022-01-01 15:42:34+00:00,2022-01-01 16:07:50+00:00,1,10.0,1.0,N,1,31.0,1.0,...,8.0,7.0,0.0,1.000000000,51.0,138,238,2022,1,0.421111
6,2,2022-01-22 00:47:41+00:00,2022-01-22 00:57:44+00:00,2,2.0,1.0,N,1,10.0,1.0,...,3.0,0.0,0.0,0,17.0,249,13,2022,1,0.167500
7,2,2022-02-20 13:19:54+00:00,2022-02-20 13:33:09+00:00,3,2.0,1.0,N,1,11.0,0.0,...,3.0,0.0,0.0,0,17.0,170,148,2022,2,0.220833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-27 23:58:15+00:00,2021-01-28 00:02:38+00:00,1,1.0,1.0,N,1,5.0,3.0,...,1.0,0.0,0.0,None,10.0,236,263,2021,1,0.073056
99996,1,2021-01-29 11:04:49+00:00,2021-01-29 11:10:21+00:00,2,1.0,1.0,N,1,5.0,3.0,...,1.0,0.0,0.0,None,9.0,234,90,2021,1,0.092222
99997,1,2021-01-29 19:18:41+00:00,2021-01-29 19:22:59+00:00,2,1.0,1.0,N,1,5.0,4.0,...,1.0,0.0,0.0,None,10.0,161,230,2021,1,0.071667
99998,1,2021-01-19 18:58:09+00:00,2021-01-19 19:02:02+00:00,1,1.0,1.0,N,1,5.0,4.0,...,2.0,0.0,0.0,None,11.0,170,229,2021,1,0.064722
99999,1,2021-01-25 18:18:26+00:00,2021-01-25 18:22:58+00:00,1,1.0,1.0,Y,1,5.0,4.0,...,2.0,0.0,0.0,None,11.0,239,143,2021,1,0.075556

In [ ]:
df2['trip_duration_minutes'] = df2['trip_duration']*60
# we made a another columns with trip duration in minutes

In [ ]:
df2['year']=df2['pickup_datetime'].dt.year

In [ ]:
df2['year'].value_counts()
#so we know in the dataset taxi trips 2021 that we have some years that is outside the intended  year. judging by the number of counts we can safely remove them .

year
2021    99320
2009      136
2008       56
2022       37
2020       13
2003        5
2011        3
2029        1
2028        1
2098        1
Name: count, dtype: int64

In [ ]:
df2  = df2[df2['year']==2021] # we are keeping 2021 data

In [ ]:
df2

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,...,imp_surcharge,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month,trip_duration,trip_duration_minutes,year
9,2,2021-01-01 00:23:21+00:00,2021-01-01 00:30:56+00:00,<NA>,3.0,None,None,0,13.0,0.0,...,0.0,None,19.0,107,237,2020,12,0.126389,7.583333,2021
10,2,2021-01-01 01:32:44+00:00,2021-01-01 02:07:14+00:00,1,18.0,1.0,N,2,50.0,1.0,...,0.0,None,60.0,127,228,2020,12,0.575000,34.500000,2021
11,2,2021-01-01 01:55:07+00:00,2021-01-01 02:13:06+00:00,1,7.0,1.0,N,2,21.0,1.0,...,0.0,None,25.0,100,116,2020,12,0.299722,17.983333,2021
12,1,2021-01-01 07:04:15+00:00,2021-01-01 07:16:54+00:00,0,8.0,1.0,N,2,21.0,0.0,...,0.0,None,22.0,132,265,2020,12,0.210833,12.650000,2021
13,1,2021-01-01 02:34:57+00:00,2021-01-01 03:00:04+00:00,1,0.0,1.0,N,1,39.0,0.0,...,0.0,None,40.0,205,256,2020,12,0.418611,25.116667,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-27 23:58:15+00:00,2021-01-28 00:02:38+00:00,1,1.0,1.0,N,1,5.0,3.0,...,0.0,None,10.0,236,263,2021,1,0.073056,4.383333,2021
99996,1,2021-01-29 11:04:49+00:00,2021-01-29 11:10:21+00:00,2,1.0,1.0,N,1,5.0,3.0,...,0.0,None,9.0,234,90,2021,1,0.092222,5.533333,2021
99997,1,2021-01-29 19:18:41+00:00,2021-01-29 19:22:59+00:00,2,1.0,1.0,N,1,5.0,4.0,...,0.0,None,10.0,161,230,2021,1,0.071667,4.300000,2021
99998,1,2021-01-19 18:58:09+00:00,2021-01-19 19:02:02+00:00,1,1.0,1.0,N,1,5.0,4.0,...,0.0,None,11.0,170,229,2021,1,0.064722,3.883333,2021
99999,1,2021-01-25 18:18:26+00:00,2021-01-25 18:22:58+00:00,1,1.0,1.0,Y,1,5.0,4.0,...,0.0,None,11.0,239,143,2021,1,0.075556,4.533333,2021

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99320 entries, 9 to 99999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   vendor_id              99320 non-null  object
 1   pickup_datetime        99320 non-null  datetime64[us, UTC]
 2   dropoff_datetime       99320 non-null  datetime64[us, UTC]
 3   passenger_count        91930 non-null  Int64
 4   trip_distance          99320 non-null  float64
 5   rate_code              91930 non-null  object
 6   store_and_fwd_flag     91930 non-null  object
 7   payment_type           99320 non-null  object
 8   fare_amount            99320 non-null  float64
 9   extra                  99320 non-null  float64
 10  mta_tax                99320 non-null  float64
 11  tip_amount             99320 non-null  float64
 12  tolls_amount           99320 non-null  float64
 13  imp_surcharge          99320 non-null  float64
 14  airport_fee            0 non-null      object
 15  total_amount           99320 non-null  float64
 16  pickup_location_id     99320 non-null  object
 17  dropoff_location_id    99320 non-null  object
 18  data_file_year         99320 non-null  Int64
 19  data_file_month        99320 non-null  Int64
 20  trip_duration          99320 non-null  float64
 21  trip_duration_minutes  99320 non-null  float64
 22  year                   99320 non-null  int32
dtypes: Int64(3), datetime64[us, UTC](2), float64(10), int32(1), object(7)
memory usage: 18.1+ MB

In [ ]:
df2.isna().sum().sort_values(ascending=False) # airport fees have lots of null values , where is rate_code ,store_and_fwd_flag,passenger_count all have 1121 null values

airport_fee              99320
rate_code                 7390
store_and_fwd_flag        7390
passenger_count           7390
dropoff_datetime             0
vendor_id                    0
pickup_datetime              0
trip_distance                0
payment_type                 0
extra                        0
fare_amount                  0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
imp_surcharge                0
total_amount                 0
pickup_location_id           0
dropoff_location_id          0
data_file_year               0
data_file_month              0
trip_duration                0
trip_duration_minutes        0
year                         0
dtype: int64

In [ ]:
df2[['rate_code','store_and_fwd_flag','passenger_count']].isna().all(axis=1).sum()

np.int64(7390)

In [ ]:
df2[df2[['rate_code','store_and_fwd_flag','passenger_count']].isna().all(axis=1)]  # the rows contains lots of information , so we can just keep it

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,...,imp_surcharge,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month,trip_duration,trip_duration_minutes,year
9,2,2021-01-01 00:23:21+00:00,2021-01-01 00:30:56+00:00,<NA>,3.0,None,None,0,13.0,0.0,...,0.0,None,19.0,107,237,2020,12,0.126389,7.583333,2021
16,2,2021-01-01 04:47:00+00:00,2021-01-01 05:01:00+00:00,<NA>,4.0,None,None,0,17.0,0.0,...,0.0,None,25.0,151,230,2020,12,0.233333,14.000000,2021
27,2,2021-01-01 00:09:00+00:00,2021-01-01 00:36:00+00:00,<NA>,5.0,None,None,0,21.0,0.0,...,0.0,None,25.0,7,82,2020,12,0.450000,27.000000,2021
38,2,2021-01-01 02:03:01+00:00,2021-01-01 02:09:25+00:00,<NA>,1.0,None,None,0,7.0,0.0,...,0.0,None,9.0,66,33,2020,12,0.106667,6.400000,2021
50,2,2021-01-01 06:10:00+00:00,2021-01-01 06:31:00+00:00,<NA>,7.0,None,None,0,21.0,0.0,...,0.0,None,31.0,80,48,2020,12,0.350000,21.000000,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99821,2,2021-01-26 15:03:33+00:00,2021-01-26 15:06:22+00:00,<NA>,1.0,None,None,0,7.0,0.0,...,0.0,None,9.0,196,196,2021,1,0.046944,2.816667,2021
99869,1,2021-01-08 08:10:35+00:00,2021-01-08 08:14:14+00:00,<NA>,1.0,None,None,0,5.0,0.0,...,0.0,None,10.0,237,237,2021,1,0.060833,3.650000,2021
99905,1,2021-01-26 17:55:32+00:00,2021-01-26 18:03:16+00:00,<NA>,2.0,None,None,0,8.0,1.0,...,0.0,None,12.0,137,114,2021,1,0.128889,7.733333,2021
99950,1,2021-01-07 06:38:07+00:00,2021-01-07 06:45:26+00:00,<NA>,1.0,None,None,0,8.0,0.0,...,0.0,None,13.0,100,162,2021,1,0.121944,7.316667,2021
99963,1,2021-01-21 19:42:34+00:00,2021-01-21 19:45:55+00:00,<NA>,1.0,None,None,0,5.0,1.0,...,0.0,None,11.0,141,263,2021,1,0.055833,3.350000,2021

In [ ]:
df2 = df2[df2['trip_duration']>0]

In [ ]:
df2.duplicated().sum()
#no duplicate values found

np.int64(0)

In [ ]:
df2[df2['trip_distance']<=0].count()

vendor_id                5382
pickup_datetime          5382
dropoff_datetime         5382
passenger_count          5205
trip_distance            5382
rate_code                5205
store_and_fwd_flag       5205
payment_type             5382
fare_amount              5382
extra                    5382
mta_tax                  5382
tip_amount               5382
tolls_amount             5382
imp_surcharge            5382
airport_fee                 0
total_amount             5382
pickup_location_id       5382
dropoff_location_id      5382
data_file_year           5382
data_file_month          5382
trip_duration            5382
trip_duration_minutes    5382
year                     5382
dtype: int64

In [ ]:
df2[df2['trip_distance'] <= 0]['trip_duration_minutes'].describe()

count    5382.000000
mean        5.981147
std        10.427545
min         0.016667
25%         1.466667
50%         2.516667
75%         4.050000
max       140.450000
Name: trip_duration_minutes, dtype: float64

In [ ]:
df3 = df2.copy()

In [ ]:
df3 = df3[df3['trip_distance']> 0]

In [ ]:
df3[df3['fare_amount']<=0]

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,...,imp_surcharge,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month,trip_duration,trip_duration_minutes,year
275,2,2021-01-01 03:16:50+00:00,2021-01-01 03:30:15+00:00,1,6.0,1.0,N,4,-20.0,-1.0,...,0.0,None,-24.0,74,224,2020,12,0.223611,13.416667,2021
306,2,2021-01-01 04:07:30+00:00,2021-01-01 04:12:14+00:00,1,1.0,1.0,N,4,-7.0,-1.0,...,0.0,None,-8.0,75,264,2020,12,0.078889,4.733333,2021
691,2,2021-01-01 04:46:56+00:00,2021-01-01 04:57:13+00:00,2,2.0,1.0,N,4,-10.0,-1.0,...,0.0,None,-14.0,137,48,2020,12,0.171389,10.283333,2021
730,2,2021-01-01 00:11:01+00:00,2021-01-01 00:13:56+00:00,1,1.0,1.0,N,4,-5.0,-1.0,...,0.0,None,-9.0,263,75,2020,12,0.048611,2.916667,2021
1163,2,2021-01-01 03:16:20+00:00,2021-01-01 03:32:54+00:00,2,8.0,1.0,N,4,-24.0,-1.0,...,0.0,None,-33.0,233,17,2020,12,0.276111,16.566667,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91588,2,2021-01-07 09:14:19+00:00,2021-01-07 09:18:32+00:00,1,1.0,1.0,N,4,-5.0,0.0,...,0.0,None,-8.0,100,164,2021,1,0.070278,4.216667,2021
91599,2,2021-01-16 13:28:46+00:00,2021-01-16 13:34:06+00:00,2,1.0,1.0,N,4,-6.0,0.0,...,0.0,None,-9.0,45,232,2021,1,0.088889,5.333333,2021
91603,2,2021-01-20 07:40:10+00:00,2021-01-20 07:48:58+00:00,1,2.0,1.0,N,3,-8.0,0.0,...,0.0,None,-11.0,79,45,2021,1,0.146667,8.800000,2021
91609,2,2021-01-24 00:12:21+00:00,2021-01-24 00:20:38+00:00,1,2.0,1.0,N,4,-9.0,-1.0,...,0.0,None,-12.0,170,144,2021,1,0.138056,8.283333,2021
91697,2,2021-01-14 15:53:19+00:00,2021-01-14 15:56:31+00:00,5,1.0,1.0,N,3,-5.0,0.0,...,0.0,None,-8.0,163,237,2021,1,0.053333,3.200000,2021

In [ ]:
df3[df3['fare_amount']<=0]['payment_type'].value_counts()

payment_type
4    181
3     82
2     70
0      9
1      3
Name: count, dtype: int64

In [ ]:
df3 = df3[df3['fare_amount']>0]  #Removed non-positive fare transactions, including disputed and no-charge/complimentary trips, as they do not
                                # represent normal revenue-generating taxi rides.

In [ ]:
df3[df3['extra'] <0]# no negetive extra

Empty DataFrame
Columns: [vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, rate_code, store_and_fwd_flag, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, imp_surcharge, airport_fee, total_amount, pickup_location_id, dropoff_location_id, data_file_year, data_file_month, trip_duration, trip_duration_minutes, year]
Index: []

[0 rows x 23 columns]

In [ ]:
df3[df3['total_amount']<=0] #no negetive or zero total amount

Empty DataFrame
Columns: [vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, rate_code, store_and_fwd_flag, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, imp_surcharge, airport_fee, total_amount, pickup_location_id, dropoff_location_id, data_file_year, data_file_month, trip_duration, trip_duration_minutes, year]
Index: []

[0 rows x 23 columns]

In [ ]:
df3[df3['passenger_count']<=0]

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,...,imp_surcharge,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month,trip_duration,trip_duration_minutes,year
12,1,2021-01-01 07:04:15+00:00,2021-01-01 07:16:54+00:00,0,8.0,1.0,N,2,21.0,0.0,...,0.0,None,22.0,132,265,2020,12,0.210833,12.650000,2021
19,1,2021-01-01 05:37:25+00:00,2021-01-01 06:28:04+00:00,0,15.0,1.0,N,2,49.0,1.0,...,0.0,None,50.0,129,131,2020,12,0.844167,50.650000,2021
31,1,2021-01-01 00:45:06+00:00,2021-01-01 00:47:58+00:00,0,1.0,1.0,N,1,5.0,3.0,...,0.0,None,10.0,233,233,2020,12,0.047778,2.866667,2021
189,1,2021-01-01 04:10:55+00:00,2021-01-01 04:41:32+00:00,0,8.0,1.0,N,2,27.0,3.0,...,0.0,None,31.0,173,48,2020,12,0.510278,30.616667,2021
196,1,2021-01-01 01:04:32+00:00,2021-01-01 01:17:11+00:00,0,3.0,1.0,N,1,12.0,1.0,...,0.0,None,16.0,95,82,2020,12,0.210833,12.650000,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99717,1,2021-01-26 15:07:33+00:00,2021-01-26 15:13:27+00:00,0,1.0,1.0,N,1,6.0,3.0,...,0.0,None,11.0,264,237,2021,1,0.098333,5.900000,2021
99718,1,2021-01-30 17:22:26+00:00,2021-01-30 17:27:35+00:00,0,1.0,1.0,N,1,6.0,3.0,...,0.0,None,11.0,143,239,2021,1,0.085833,5.150000,2021
99746,1,2021-01-06 17:08:20+00:00,2021-01-06 17:26:13+00:00,0,2.0,1.0,N,1,12.0,4.0,...,0.0,None,20.0,140,161,2021,1,0.298056,17.883333,2021
99791,1,2021-01-27 21:46:59+00:00,2021-01-27 21:56:51+00:00,0,2.0,1.0,Y,2,10.0,3.0,...,0.0,None,13.0,125,137,2021,1,0.164444,9.866667,2021
99954,1,2021-01-27 15:40:02+00:00,2021-01-27 15:48:17+00:00,0,1.0,1.0,N,1,8.0,3.0,...,0.0,None,13.0,161,236,2021,1,0.137500,8.250000,2021

In [ ]:
df3 = df3[(df3['passenger_count'] > 0) |(df3['passenger_count'].isna())]#removed rows with customer count  0 or less than 0

In [ ]:
df3['passenger_count'].isna().sum()

np.int64(6701)

In [ ]:
df3['fare_amount'].sort_values(ascending=False)

49335    350.0
69576    295.0
17438    225.0
28203    214.0
59574    206.0
         ...
16457      3.0
17481      3.0
29789      2.0
9042       2.0
30897      1.0
Name: fare_amount, Length: 91214, dtype: float64

In [ ]:
df3[df3['fare_amount']==3]# we can see again the travel duration in munites is veryy suspicious as it can't be below 1 minutes

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,...,imp_surcharge,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month,trip_duration,trip_duration_minutes,year
2645,1,2021-01-01 03:14:47+00:00,2021-01-01 03:14:55+00:00,1,4.0,1.0,N,3,3.0,1.0,...,0.0,None,4.0,151,24,2020,12,0.002222,0.133333,2021
5454,1,2021-01-01 02:25:05+00:00,2021-01-01 02:31:26+00:00,1,2.0,1.0,N,2,3.0,3.0,...,0.0,None,7.0,100,164,2020,12,0.105833,6.350000,2021
5935,1,2021-01-05 12:21:53+00:00,2021-01-05 12:22:58+00:00,1,2.0,1.0,N,3,3.0,0.0,...,0.0,None,4.0,24,24,2021,1,0.018056,1.083333,2021
6182,1,2021-01-06 15:09:00+00:00,2021-01-06 15:09:10+00:00,1,2.0,1.0,N,4,3.0,3.0,...,0.0,None,6.0,68,68,2021,1,0.002778,0.166667,2021
6626,1,2021-01-03 13:09:06+00:00,2021-01-03 13:09:17+00:00,1,4.0,1.0,N,4,3.0,0.0,...,0.0,None,3.0,74,74,2021,1,0.003056,0.183333,2021
6947,1,2021-01-08 02:36:27+00:00,2021-01-08 02:36:29+00:00,1,3.0,1.0,N,2,3.0,3.0,...,0.0,None,6.0,186,186,2021,1,0.000556,0.033333,2021
7057,1,2021-01-05 04:52:24+00:00,2021-01-05 04:52:25+00:00,1,5.0,1.0,N,2,3.0,3.0,...,0.0,None,6.0,48,48,2021,1,0.000278,0.016667,2021
16423,1,2021-01-02 17:55:36+00:00,2021-01-02 17:57:24+00:00,1,6.0,1.0,N,3,3.0,3.0,...,0.0,None,6.0,100,100,2021,1,0.030000,1.800000,2021
16457,1,2021-01-21 11:29:31+00:00,2021-01-21 11:30:20+00:00,1,1.0,1.0,N,2,3.0,3.0,...,0.0,None,6.0,161,161,2021,1,0.013611,0.816667,2021
16560,1,2021-01-20 06:59:14+00:00,2021-01-20 06:59:43+00:00,1,4.0,1.0,N,2,3.0,0.0,...,0.0,None,3.0,244,244,2021,1,0.008056,0.483333,2021
16890,1,2021-01-21 17:07:29+00:00,2021-01-21 17:07:41+00:00,1,2.0,1.0,N,2,3.0,4.0,...,0.0,None,7.0,161,161,2021,1,0.003333,0.200000,2021
16956,1,2021-01-31 00:55:25+00:00,2021-01-31 00:55:33+00:00,1,3.0,1.0,Y,1,3.0,3.0,...,0.0,None,10.0,229,229,2021,1,0.002222,0.133333,2021
17435,1,2021-01-07 06:43:31+00:00,2021-01-07 06:43:46+00:00,1,3.0,1.0,N,3,3.0,3.0,...,0.0,None,6.0,107,107,2021,1,0.004167,0.250000,2021
17481,1,2021-01-31 19:57:35+00:00,2021-01-31 19:57:42+00:00,1,3.0,1.0,N,3,3.0,1.0,...,0.0,None,4.0,226,226,2021,1,0.001944,0.116667,2021
27079,1,2021-01-19 01:37:41+00:00,2021-01-19 01:37:48+00:00,1,8.0,1.0,N,3,3.0,3.0,...,0.0,None,6.0,100,100,2021,1,0.001944,0.116667,2021
27201,1,2021-01-17 19:03:31+00:00,2021-01-17 19:04:36+00:00,1,2.0,1.0,N,3,3.0,3.0,...,0.0,None,6.0,137,137,2021,1,0.018056,1.083333,2021
27315,1,2021-01-19 18:21:43+00:00,2021-01-19 18:21:49+00:00,1,3.0,1.0,N,2,3.0,4.0,...,0.0,None,7.0,107,234,2021,1,0.001667,0.100000,2021
28125,1,2021-01-09 20:44:46+00:00,2021-01-09 20:44:56+00:00,1,1.0,1.0,N,2,3.0,1.0,...,0.0,None,4.0,145,145,2021,1,0.002778,0.166667,2021
48538,1,2021-01-23 13:18:20+00:00,2021-01-23 13:19:55+00:00,2,6.0,1.0,N,2,3.0,0.0,...,0.0,None,4.0,244,244,2021,1,0.026389,1.583333,2021
48624,1,2021-01-10 11:18:48+00:00,2021-01-10 11:19:20+00:00,1,1.0,1.0,N,2,3.0,3.0,...,0.0,None,6.0,48,48,2021,1,0.008889,0.533333,2021
48975,1,2021-01-26 09:42:18+00:00,2021-01-26 09:42:20+00:00,1,9.0,1.0,N,1,3.0,3.0,...,0.0,None,10.0,237,237,2021,1,0.000556,0.033333,2021
49319,1,2021-01-07 22:02:08+00:00,2021-01-07 22:02:40+00:00,1,3.0,1.0,Y,3,3.0,3.0,...,0.0,None,6.0,137,137,2021,1,0.008889,0.533333,2021
58984,1,2021-01-26 21:04:13+00:00,2021-01-26 21:05:00+00:00,<NA>,2.0,None,None,0,3.0,1.0,...,0.0,None,8.0,263,263,2021,1,0.013056,0.783333,2021
59345,1,2021-01-12 10:41:07+00:00,2021-01-12 10:42:08+00:00,3,4.0,1.0,N,3,3.0,3.0,...,0.0,None,6.0,186,186,2021,1,0.016944,1.016667,2021
69670,1,2021-01-06 13:04:30+00:00,2021-01-06 13:07:48+00:00,1,2.0,1.0,N,1,3.0,3.0,...,0.0,None,16.0,68,68,2021,1,0.055000,3.300000,2021
70171,1,2021-01-06 14:14:01+00:00,2021-01-06 14:14:22+00:00,2,1.0,1.0,N,3,3.0,0.0,...,0.0,None,3.0,151,151,2021,1,0.005833,0.350000,2021
70192,1,2021-01-16 20:14:03+00:00,2021-01-16 20:14:33+00:00,1,1.0,1.0,N,2,3.0,3.0,...,0.0,None,6.0,48,48,2021,1,0.008333,0.500000,2021
70316,1,2021-01-31 00:19:09+00:00,2021-01-31 00:20:32+00:00,1,2.0,1.0,N,2,3.0,3.0,...,0.0,None,7.0,161,161,2021,1,0.023056,1.383333,2021
70635,1,2021-01-10 13:07:49+00:00,2021-01-10 13:07:55+00:00,1,13.0,1.0,N,2,3.0,0.0,...,0.0,None,3.0,151,151,2021,1,0.001667,0.100000,2021
70747,1,2021-01-03 13:10:39+00:00,2021-01-03 13:10:47+00:00,1,2.0,1.0,Y,4,3.0,3.0,...,0.0,None,6.0,90,90,2021,1,0.002222,0.133333,2021
70768,1,2021-01-15 19:23:03+00:00,2021-01-15 19:23:21+00:00,1,9.0,1.0,N,3,3.0,1.0,...,0.0,None,4.0,116,116,2021,1,0.005000,0.300000,2021
80304,1,2021-01-02 18:44:15+00:00,2021-01-02 18:44:22+00:00,1,9.0,1.0,N,3,3.0,1.0,...,0.0,None,4.0,132,132,2021,1,0.001944,0.116667,2021
80573,1,2021-01-19 09:14:35+00:00,2021-01-19 09:14:47+00:00,1,2.0,1.0,N,2,3.0,0.0,...,0.0,None,3.0,145,145,2021,1,0.003333,0.200000,2021
80783,1,2021-01-12 11:54:18+00:00,2021-01-12 11:54:31+00:00,1,3.0,1.0,N,3,3.0,3.0,...,0.0,None,6.0,79,79,2021,1,0.003611,0.216667,2021
80807,1,2021-01-30 18:56:29+00:00,2021-01-30 18:56:43+00:00,1,2.0,1.0,N,4,3.0,0.0,...,0.0,None,3.0,75,75,2021,1,0.003889,0.233333,2021
81194,1,2021-01-10 20:08:24+00:00,2021-01-10 20:08:46+00:00,1,1.0,1.0,N,4,3.0,1.0,...,0.0,None,4.0,138,138,2021,1,0.006111,0.366667,2021
93604,2,2021-01-24 14:44:00+00:00,2021-01-24 14:52:38+00:00,1,2.0,1.0,N,1,3.0,0.0,...,0.0,None,11.0,79,186,2021,1,0.143889,8.633333,2021

In [ ]:
df3 = df3[df3['trip_duration_minutes']>1]

In [ ]:
df3['total_amount'].sort_values(ascending=False)

49335    357.0
69576    311.0
28203    276.0
6040     258.0
80609    252.0
         ...
57146      4.0
5935       4.0
14600      4.0
36988      4.0
55567      4.0
Name: total_amount, Length: 91108, dtype: float64

In [ ]:
df3['trip_distance'].sort_values(ascending=False) # trip distance falls in  expected range

81224    114328.0
94404     51682.0
73298     28399.0
49335       119.0
6040         93.0
           ...
99992         1.0
99991         1.0
99990         1.0
99989         1.0
99988         1.0
Name: trip_distance, Length: 91108, dtype: float64

In [ ]:
df3['travel_month']=df3['pickup_datetime'].dt.month_name()

In [ ]:
df3

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,...,airport_fee,total_amount,pickup_location_id,dropoff_location_id,data_file_year,data_file_month,trip_duration,trip_duration_minutes,year,travel_month
9,2,2021-01-01 00:23:21+00:00,2021-01-01 00:30:56+00:00,<NA>,3.0,None,None,0,13.0,0.0,...,None,19.0,107,237,2020,12,0.126389,7.583333,2021,January
10,2,2021-01-01 01:32:44+00:00,2021-01-01 02:07:14+00:00,1,18.0,1.0,N,2,50.0,1.0,...,None,60.0,127,228,2020,12,0.575000,34.500000,2021,January
11,2,2021-01-01 01:55:07+00:00,2021-01-01 02:13:06+00:00,1,7.0,1.0,N,2,21.0,1.0,...,None,25.0,100,116,2020,12,0.299722,17.983333,2021,January
14,1,2021-01-01 00:22:56+00:00,2021-01-01 00:44:31+00:00,1,6.0,1.0,N,1,21.0,3.0,...,None,32.0,43,211,2020,12,0.359722,21.583333,2021,January
16,2,2021-01-01 04:47:00+00:00,2021-01-01 05:01:00+00:00,<NA>,4.0,None,None,0,17.0,0.0,...,None,25.0,151,230,2020,12,0.233333,14.000000,2021,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-27 23:58:15+00:00,2021-01-28 00:02:38+00:00,1,1.0,1.0,N,1,5.0,3.0,...,None,10.0,236,263,2021,1,0.073056,4.383333,2021,January
99996,1,2021-01-29 11:04:49+00:00,2021-01-29 11:10:21+00:00,2,1.0,1.0,N,1,5.0,3.0,...,None,9.0,234,90,2021,1,0.092222,5.533333,2021,January
99997,1,2021-01-29 19:18:41+00:00,2021-01-29 19:22:59+00:00,2,1.0,1.0,N,1,5.0,4.0,...,None,10.0,161,230,2021,1,0.071667,4.300000,2021,January
99998,1,2021-01-19 18:58:09+00:00,2021-01-19 19:02:02+00:00,1,1.0,1.0,N,1,5.0,4.0,...,None,11.0,170,229,2021,1,0.064722,3.883333,2021,January
99999,1,2021-01-25 18:18:26+00:00,2021-01-25 18:22:58+00:00,1,1.0,1.0,Y,1,5.0,4.0,...,None,11.0,239,143,2021,1,0.075556,4.533333,2021,January

In [ ]:
print(f"Original rows: {len(df):,}")
print(f"Cleaned rows: {len(df3):,}")
print(f"Rows removed: {len(df) - len(df3):,}")
print(f"Retention rate: {len(df3) / len(df) * 100:.2f}%")

#I started with 100,000 records, applied data-quality and business-rule checks, and retained 91,216 valid observations for analysis.

Original rows: 100,000
Cleaned rows: 91,108
Rows removed: 8,892
Retention rate: 91.11%

In [ ]:
df3.to_parquet(r'D:\nyc_taxi_trips\taxi_trips_analysis.parquet',index=False)